from util.color import bcolors
def intro():
    print bcolors.Red + "SYSCORE Lab. CSH"
    print "################## IF YOU CAN CATCH ME (ver 0.1) ################## "
    print bcolors.Yellow + ":I::;II;::::::::;;::::::::::;IIIII::::;II;;;I;:::;I;;;;III;;"
    print " =::::::::;I;::::::::::::::::::::::::::::::::::::::::::::::I~"
    print " `=::::::i++i:::::::::::::::::::::::::::::::::::::::::::::;I"
    print "` I:::::i++i::::::::::::::::::::::::::::::::::::::::::::::=  `"
    print ".=:::::I=I::::::::::::::::::::::::::::::::::::::::;++::::;: `"
    print " .=::::::::::::::==I;;;;I==:::::::::===II===:::::::Ii::::::i `"
    print "  ~I:::;i;::::;+;          ;i;:::i=:        :=i:::::::::::=: `"
    print " ` =::I+i::::=I         ``   ;i:+              iI::::::::=`"
    print "  .=:::::::::+        +8oo8O` :O  `ooOOo.       i;:::::::;"
    print "  =:::::::::=~       :EIMM+iE :~  M=OME=M        o:::::::i`"
    print "  ~=::::;IIIii        i8OoO8. II:.;Eoo+OO        o:::::::i`"
    print " ` `=::=i;:I~:+         `.   i:::I~ :;;`       =Ii;II=::="
    print "    =::I;::=8~Ii:           :+:::i`           .+::o;:I+:= `"
    print " ` :;:::;:::;o::;iI;:~~~:;Ii;::;=;iI;~     ~;==::o;::i::I~"
    print "   =:::::::::~+i::::::;::::::::;:::::;=i===:::;++~::::::I."
    print "   `=;::::::::::iii;:::::::::::::::::::::::=ii=:::::::::= `"
    print "     ~=:::::=i:::::I======II;::;:II=ii===i=:::::II:::::="
    print "     :I::::++;::::::::::;I `.;o;8`   +~:::::::=+i+::::I~"
    print "     =::::::::::::::::::;=I;:i;:=;;;;i:::::::I+i+;:::::I"
    print "     `=:::::::Ii+;:::::::::::::::::::::::::::;=I::::::=`"
    print "      +;;::::i+i+:::::::::::::::::::::::::::::::::::I+`"
    print "     `i =:::;++i::::::::::::::::::::::::::::::=+::::= o"
    print "     I. i:::::::;;:::::::;;::::::::::::::::::=+I::::=`i`"
    print "     I~ ~==II;::~~IIIIoi:..~:IiI==;;;;I+====II;;I==II I."
    print "      I=I+~            .;;:~;oOO8=I~::;`           O;II"
    print "        o:+...........`````` ~EO8 ``    ``        :=i."
    print "        o~OiiO8888oiiOEEEEEOiEooo#+#####O+oEEEEE8+E~o  `"
    print "        ;I=i=+oooo+==ioooooi+8ooO8ioooooi==OOOOOoIO~o"
    print "         O~8I==========I==I===oOiI==I==I===I====Iii;I"
    print "       ` ;I:++i=iiio++++++++oo++++++O++++++O===iOi~O"
    print "         +::=I+    =+o+i++o.        =io+o+i=   o=;:=;"
    print "        `oI:;+i   `   ~+~+           i:;;      +iI:;O"
    print "        `o:oIO+i`      o:i.          o:O      ;i8~O:o`"
    print "       ` :+:==I8`      IOOo         IE8+     `O+=O:Ii"
    print "           ;I=I~       .+;o         o;=I      ~=oI=~"
    print "                       `O=o~        oIII"
    print "                .II;. .O  .I       :+  Ei :i+o=`"
    print "               8MMMMMMMMM8MM`      #MMMMMMMMMMMM~"
    print "               MMMMMMMMMMMM;        MMMMMMMMMMMM."
    print "                :=ii=;~`I~            .  .~;;:." +bcolors.White